clear;
clc;
close all;

%% Riproducibilità
rng(42);

%% Immagini
path = fullfile('Dataset', 'Da usare');

imgs = imageDatastore(path, ...
    "IncludeSubfolders", true, ...
    "LabelSource", "foldernames");

%% Split dataset (70-15-15)
[imgsTrain, imgsTemp] = splitEachLabel(imgs, 0.7, "randomized");
[imgsVal, ~] = splitEachLabel(imgsTemp, 0.5, "randomized");

%preluLayer
%z-score

%% Architettura cnn
miniBatchSize = 32;
validationFrequency = ceil((numel(imgsTrain.Files)/miniBatchSize)/3);

layers = [
    imageInputLayer([224 224 1], ...
    "Normalization", "zscore")

    convolution2dLayer(5, 8, ...
        "Padding","same", ...
        "WeightsInitializer","he")
    batchNormalizationLayer
    reluLayer

    convolution2dLayer(3, 16, ...
        "Padding","same", ...
        "WeightsInitializer","he")
    batchNormalizationLayer
    reluLayer
    maxPooling2dLayer(2, "Stride", 2)

    convolution2dLayer(3, 32, ...
        "Padding","same", ...
        "WeightsInitializer","he")
    batchNormalizationLayer
    reluLayer
    maxPooling2dLayer(2, "Stride", 2)

    dropoutLayer(0.3)

    fullyConnectedLayer(numel(categories(imgs.Labels)))
    softmaxLayer
    classificationLayer
    ];

%% Opzioni

options = trainingOptions("sgdm", ...
    "ExecutionEnvironment", "cpu", ...
    "DispatchInBackground", true, ...
    "ValidationPatience", 5, ...
    "InitialLearnRate", 3e-4, ...
    "LearnRateSchedule", "piecewise", ...
    "LearnRateDropFactor", 0.1, ...
    "LearnRateDropPeriod", 15, ...
    "MaxEpochs", 30, ...
    "MiniBatchSize", miniBatchSize, ...
    "Shuffle", "every-epoch", ...
    "Plots", "training-progress", ...
    "ValidationData", imgsVal, ...
    "ValidationFrequency", validationFrequency, ...
    "Verbose", false);
%%
augmenter = imageDataAugmenter( ...
    "RandXTranslation", [-5 5], ...
    "RandYTranslation", [-5 5], ...
    "RandScale", [0.95 1.05]);

augImgsTrain = augmentedImageDatastore( ...
    [224 224 1], ...
    imgsTrain, ...
    "DataAugmentation", augmenter);

%% Addestramento
net = trainNetwork(augImgsTrain, layers, options);

%% Salvataggio
save('rete11.mat', 'net', 'options');