clear;
clc;
close all;

%% Riproducibilità
rng(42);

%% Immagini
path = fullfile('Dataset', 'Da usare');

imgs = imageDatastore(path, ...
    "IncludeSubfolders", true, ...
    "LabelSource", "foldernames");

%% Split dataset (70-15-15)
[imgsTrain, imgsTemp] = splitEachLabel(imgs, 0.7, "randomized");
[imgsVal, ~] = splitEachLabel(imgsTemp, 0.5, "randomized");

%% Architettura cnn
miniBatchSize = 64;
validationFrequency = ceil((numel(imgsTrain.Files)/miniBatchSize)/3);

layers = [
    imageInputLayer([224 224 1], ...
    "Normalization", "rescale-zero-one")

    convolution2dLayer(5, 8, ...
        "WeightsInitializer","he", ...
        "Name","conv1")
    batchNormalizationLayer
    reluLayer
    maxPooling2dLayer(2, "Stride", 2)

    convolution2dLayer(3, 16, ...
        "WeightsInitializer","he", ...
        "Name","conv2")
    batchNormalizationLayer
    reluLayer
    maxPooling2dLayer(2, "Stride", 2)

    dropoutLayer(0.3)

    fullyConnectedLayer(numel(categories(imgs.Labels)))
    softmaxLayer
    classificationLayer
    ];

%% Opzioni

options = trainingOptions("sgdm", ...
    "ExecutionEnvironment", "cpu", ...
    "DispatchInBackground", true, ...
    "ValidationPatience", 5, ...
    "InitialLearnRate", 5e-4, ...
    "LearnRateSchedule", "piecewise", ...
    "LearnRateDropFactor", 0.1, ...
    "LearnRateDropPeriod", 15, ...
    "L2Regularization", 1e-4, ...
    "MaxEpochs", 40, ...
    "MiniBatchSize", miniBatchSize, ...
    "Shuffle", "every-epoch", ...
    "Plots", "training-progress", ...
    "ValidationData", imgsVal, ...
    "ValidationFrequency", validationFrequency, ...
    "Verbose", false);

%% Addestramento
net = trainNetwork(imgsTrain, layers, options);

%% Salvataggio
save('rete1.mat', 'net', 'options', 'layers');